name: Ward Pull Requests

on: [pull_request]

jobs:
  test:
    name: Testing on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: dschep/install-poetry-action@v1.3
      with:
        version: 1.0.3
        create_virtualenvs: true
    - name: Run tests with Ward
      run: |
        poetry install
        poetry run coverage run -m ward
    - name: Upload coverage report to codecov
      run: |
        poetry run coverage xml -i
        bash <(curl -s https://codecov.io/bash)
      shell: bash
