name: Ward Pull Requests

on: [pull_request]

jobs:
  test:
    name: Testing on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Run tests with Ward
      uses: abatilo/actions-poetry@v1.5.0
      with:
        poetry_version: 1.0.3
        python_version: ${{ matrix.python-version }}
        args: run ward
